springdoc:
  api-docs:
    enabled: true # enable docs
  swagger-ui:
    enabled: true # enable docs ui
  author: <your docs auth>
  title: <your docs title>
  version: <your docs version>
  authHeader: <your api authentication request head>
