springdoc:
  api-docs:
    enabled: true # enable docs
  swagger-ui:
    enabled: true # enable docs ui
  author: <your docs auth>
  title: <your docs title>
  version: <your docs version>
  authHeader: <your api authentication request head>

spring:
  mail:
    host: <your email server host>
    port: <your email server port>
    username: <your email address>
    password: <your password>
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
