springdoc:
  swagger-ui:
    use-root-path: true # set project web root index to api doc
  group-configs:
    - group: default # set a default group
      paths-to-match:
        - /**

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
